### PR TITLE
Fixing Data Race Conditions caught by TSAN

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Updating and reopening #37 :) 
cc @benpious @rudro

### CODE REVIEW

**Comment by muukii** [comment]
@LucianoPAlmeida 

Hello,
First of all, I'm not a maintainer and contributor. but I'm so interested in this library.
I've tried AtomicInt on this PR's branch. However, I faced a memory issue when running concurrently (Iterating 10000 applying).
It works on master branch.

I have not yet dived deeply. but Do you have any idea?

BTW, I'm also this conversation in Swift Forum.
https://forums.swift.org/t/low-level-atomic-operations/34683
https://github.com/apple/swift-evolution/blob/master/proposals/0282-atomics.md

Thanks.

**Comment by LucianoPAlmeida** [comment]
Hi @muukii :)
Thanks for reporting, I'm not really sure what the issues could be (if it is sync issues maybe I know), the only thing I've done was make sure operations were atomic so TSan is happy. Could you shard the snippet you having issues with? 
This library seems unmaintained since this PR is opened for a while... but I'll keep this opened for the reference

**Comment by muukii** [comment]
@LucianoPAlmeida 
thanks.
It's a little bit difficult to reproduce that, I'll share with you if I created a simple project that can reproduce it.

> This library seems unmaintained since this PR is opened for a while... but I'll keep this opened for the reference

I think so too, but this repo's approach that locking-free technique is so interesting for me.
Maybe Swift stdlib solve it in the future...

**Comment by LucianoPAlmeida** [comment]
> It's a little bit difficult to reproduce that, I'll share with you if I created a simple project that can reproduce it.
> 

No problem, I just send a commit reverting a change (involving memory order and synchronization) which I suspect could cause issues, so if you can test it again. Thanks :) 

> Maybe Swift stdlib solve it in the future...

Let's hope so, SE-0282 seems promising \o/

**Pull request closed without merging**
